#  SConscript for libsrc
#
#  to customize fill in package dependencies
#
#  ejw, 16-apr-2013


Import('*')
from halld_lib import define_dependencies, buildLib

 
#  set package dependencies
define_dependencies(libEnv,'cmsg root')


#  build the lib
buildLib(libEnv)
