/********************************************************************
* Dialog_IndivHists_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dialog_IndivHists_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDialog_IndivHists_Dict();
extern void G__cpp_setup_inheritanceDialog_IndivHists_Dict();
extern void G__cpp_setup_typetableDialog_IndivHists_Dict();
extern void G__cpp_setup_memvarDialog_IndivHists_Dict();
extern void G__cpp_setup_globalDialog_IndivHists_Dict();
extern void G__cpp_setup_memfuncDialog_IndivHists_Dict();
extern void G__cpp_setup_funcDialog_IndivHists_Dict();
extern void G__set_cpp_environmentDialog_IndivHists_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Dialog_IndivHists.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TClass;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TBuffer;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TMemberInspector;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TObject;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_string;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TTimer;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_Event_t;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TQObject;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGWindow;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGObject;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGFrame;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGVerticalFrame;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGMainFrame;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGCheckButton;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TGRadioButton;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TCanvas;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TVirtualPad;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_Dialog_IndivHists;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_Dialog_IndivHistscLcLdisplay_style;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Dialog_IndivHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
