/********************************************************************
* Dialog_SelectTree_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dialog_SelectTree_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDialog_SelectTree_Dict();
extern void G__cpp_setup_inheritanceDialog_SelectTree_Dict();
extern void G__cpp_setup_typetableDialog_SelectTree_Dict();
extern void G__cpp_setup_memvarDialog_SelectTree_Dict();
extern void G__cpp_setup_globalDialog_SelectTree_Dict();
extern void G__cpp_setup_memfuncDialog_SelectTree_Dict();
extern void G__cpp_setup_funcDialog_SelectTree_Dict();
extern void G__set_cpp_environmentDialog_SelectTree_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Dialog_SelectTree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TClass;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TBuffer;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TMemberInspector;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TObject;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_string;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TTimer;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TQObject;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGWindow;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGPicture;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGObject;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGFrame;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGTextButton;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGMainFrame;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGCanvas;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGRadioButton;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGListTreeItem;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TGListTree;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_Dialog_SelectTree;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_vectorlEtree_info_tcOallocatorlEtree_info_tgRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_reverse_iteratorlEvectorlEtree_info_tcOallocatorlEtree_info_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_vectorlEvectorlEtree_info_tcOallocatorlEtree_info_tgRsPgRcOallocatorlEvectorlEtree_info_tcOallocatorlEtree_info_tgRsPgRsPgRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_reverse_iteratorlEvectorlEvectorlEtree_info_tcOallocatorlEtree_info_tgRsPgRcOallocatorlEvectorlEtree_info_tcOallocatorlEtree_info_tgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_maplEstringcOserver_info_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOserver_info_tgRsPgRsPgR;
extern G__linked_taginfo G__Dialog_SelectTree_DictLN_maplEtree_id_tcOTGListTreeItemmUcOlesslEtree_id_tgRcOallocatorlEpairlEconstsPtree_id_tcOTGListTreeItemmUgRsPgRsPgR;

/* STUB derived class for protected member access */
