//
// File generated by rootcint at Tue Apr  9 17:57:32 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Dialog_SaveHists_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dialog_SaveHists_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Dialog_SaveHists_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Dialog_SaveHists(void *p);
   static void deleteArray_Dialog_SaveHists(void *p);
   static void destruct_Dialog_SaveHists(void *p);
   static void streamer_Dialog_SaveHists(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Dialog_SaveHists*)
   {
      ::Dialog_SaveHists *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Dialog_SaveHists >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Dialog_SaveHists", ::Dialog_SaveHists::Class_Version(), "./Dialog_SaveHists.h", 32,
                  typeid(::Dialog_SaveHists), DefineBehavior(ptr, ptr),
                  &::Dialog_SaveHists::Dictionary, isa_proxy, 0,
                  sizeof(::Dialog_SaveHists) );
      instance.SetDelete(&delete_Dialog_SaveHists);
      instance.SetDeleteArray(&deleteArray_Dialog_SaveHists);
      instance.SetDestructor(&destruct_Dialog_SaveHists);
      instance.SetStreamerFunc(&streamer_Dialog_SaveHists);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Dialog_SaveHists*)
   {
      return GenerateInitInstanceLocal((::Dialog_SaveHists*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Dialog_SaveHists*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Dialog_SaveHists::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Dialog_SaveHists::Class_Name()
{
   return "Dialog_SaveHists";
}

//______________________________________________________________________________
const char *Dialog_SaveHists::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Dialog_SaveHists*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Dialog_SaveHists::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Dialog_SaveHists*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Dialog_SaveHists::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Dialog_SaveHists*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Dialog_SaveHists::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Dialog_SaveHists*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Dialog_SaveHists::Streamer(TBuffer &R__b)
{
   // Stream an object of class Dialog_SaveHists.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TGMainFrame::Streamer(R__b);
      R__b >> timer;
      R__b >> sleep_time;
      R__b >> last_called;
      R__b >> last_ping_time;
      R__b >> last_hist_time;
      {
         vector<hid_t> &R__stl =  last_hids;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("last_hids streamer","Missing the TClass object for hid_t!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            hid_t R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      {
         map<hid_t,TGListTreeItem*> &R__stl =  server_items;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("server_items streamer","Missing the TClass object for hid_t!");
            return;
         }
         TClass *R__tcl2 = TBuffer::GetClass(typeid(TGListTreeItem));
         if (R__tcl2==0) {
            Error("server_items streamer","Missing the TClass object for TGListTreeItem!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         for (R__i = 0; R__i < R__n; R__i++) {
            hid_t R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            TGListTreeItem* R__t2;
            if (R__b.GetInfo() && R__b.GetInfo()->GetOldVersion()<=3) {
               R__ASSERT(0);// TGListTreeItem is abstract. We assume that older file could not be produced using this streaming method.
            } else {
               R__t2 = (TGListTreeItem*)R__b.ReadObjectAny(R__tcl2);
            }
            typedef hid_t Value_t;
            std::pair<Value_t const, TGListTreeItem* > R__t3(R__t,R__t2);
            R__stl.insert(R__t3);
         }
      }
      {
         map<hid_t,TGListTreeItem*> &R__stl =  hist_items;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("hist_items streamer","Missing the TClass object for hid_t!");
            return;
         }
         TClass *R__tcl2 = TBuffer::GetClass(typeid(TGListTreeItem));
         if (R__tcl2==0) {
            Error("hist_items streamer","Missing the TClass object for TGListTreeItem!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         for (R__i = 0; R__i < R__n; R__i++) {
            hid_t R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            TGListTreeItem* R__t2;
            if (R__b.GetInfo() && R__b.GetInfo()->GetOldVersion()<=3) {
               R__ASSERT(0);// TGListTreeItem is abstract. We assume that older file could not be produced using this streaming method.
            } else {
               R__t2 = (TGListTreeItem*)R__b.ReadObjectAny(R__tcl2);
            }
            typedef hid_t Value_t;
            std::pair<Value_t const, TGListTreeItem* > R__t3(R__t,R__t2);
            R__stl.insert(R__t3);
         }
      }
      R__b >> canvas;
      R__b >> listTree;
      R__b >> viewByObject;
      R__b >> viewByServer;
      R__b >> const_cast<  TGPicture* &>( folder_t );
      R__b >> const_cast<  TGPicture* &>( ofolder_t );
      R__b >> const_cast<  TGPicture* &>( h1_s );
      R__b >> const_cast<  TGPicture* &>( h1_t );
      R__b >> const_cast<  TGPicture* &>( h2_s );
      R__b >> const_cast<  TGPicture* &>( h2_t );
      R__b >> const_cast<  TGPicture* &>( h3_s );
      R__b >> const_cast<  TGPicture* &>( h3_t );
      R__b >> const_cast<  TGPicture* &>( pack_t );
      R__b >> const_cast<  TGPicture* &>( hdisk_t );
      R__b >> const_cast<  TGPicture* &>( checked_t );
      R__b >> const_cast<  TGPicture* &>( unchecked_t );
      R__b >> tosave;
      R__b >> displaybar;
      R__b >> thefileinfo;
      R__b >> hist_get_size;
      {
         map<string,int> &R__stl =  histtosave;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         for (R__i = 0; R__i < R__n; R__i++) {
            string R__t;
            {TString R__str;
             R__str.Streamer(R__b);
             R__t = R__str.Data();}
            int R__t2;
            R__b >> R__t2;
            typedef string Value_t;
            std::pair<Value_t const, int > R__t3(R__t,R__t2);
            R__stl.insert(R__t3);
         }
      }
      R__b >> verticalframe;
      R__b >> progressbar;
      R__b >> mainframe;
      R__b.CheckByteCount(R__s, R__c, Dialog_SaveHists::IsA());
   } else {
      R__c = R__b.WriteVersion(Dialog_SaveHists::IsA(), kTRUE);
      TGMainFrame::Streamer(R__b);
      R__b << timer;
      R__b << sleep_time;
      R__b << last_called;
      R__b << last_ping_time;
      R__b << last_hist_time;
      {
         vector<hid_t> &R__stl =  last_hids;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("last_hids streamer","Missing the TClass object for hid_t!");
            return;
         }
            vector<hid_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((hid_t*)&(*R__k),R__tcl1);
            }
         }
      }
      {
         map<hid_t,TGListTreeItem*> &R__stl =  server_items;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("server_items streamer","Missing the TClass object for hid_t!");
            return;
         }
         TClass *R__tcl2 = TBuffer::GetClass(typeid(TGListTreeItem));
         if (R__tcl2==0) {
            Error("server_itemsstreamer","Missing the TClass object for TGListTreeItem!");
            return;
         }
            map<hid_t,TGListTreeItem*>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((hid_t*)&((*R__k).first ),R__tcl1);
            R__b.WriteObjectAny(((*R__k).second),R__tcl2);
            }
         }
      }
      {
         map<hid_t,TGListTreeItem*> &R__stl =  hist_items;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(hid_t));
         if (R__tcl1==0) {
            Error("hist_items streamer","Missing the TClass object for hid_t!");
            return;
         }
         TClass *R__tcl2 = TBuffer::GetClass(typeid(TGListTreeItem));
         if (R__tcl2==0) {
            Error("hist_itemsstreamer","Missing the TClass object for TGListTreeItem!");
            return;
         }
            map<hid_t,TGListTreeItem*>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((hid_t*)&((*R__k).first ),R__tcl1);
            R__b.WriteObjectAny(((*R__k).second),R__tcl2);
            }
         }
      }
      R__b << canvas;
      R__b << listTree;
      R__b << viewByObject;
      R__b << viewByServer;
      R__b << const_cast<  TGPicture* &>( folder_t );
      R__b << const_cast<  TGPicture* &>( ofolder_t );
      R__b << const_cast<  TGPicture* &>( h1_s );
      R__b << const_cast<  TGPicture* &>( h1_t );
      R__b << const_cast<  TGPicture* &>( h2_s );
      R__b << const_cast<  TGPicture* &>( h2_t );
      R__b << const_cast<  TGPicture* &>( h3_s );
      R__b << const_cast<  TGPicture* &>( h3_t );
      R__b << const_cast<  TGPicture* &>( pack_t );
      R__b << const_cast<  TGPicture* &>( hdisk_t );
      R__b << const_cast<  TGPicture* &>( checked_t );
      R__b << const_cast<  TGPicture* &>( unchecked_t );
      R__b << tosave;
      R__b << displaybar;
      R__b << thefileinfo;
      R__b << hist_get_size;
      {
         map<string,int> &R__stl =  histtosave;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            map<string,int>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            {TString R__str(((*R__k).first ).c_str());
             R__str.Streamer(R__b);};
            R__b << ((*R__k).second);
            }
         }
      }
      R__b << verticalframe;
      R__b << progressbar;
      R__b << mainframe;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void Dialog_SaveHists::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Dialog_SaveHists.
      TClass *R__cl = ::Dialog_SaveHists::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*timer", &timer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sleep_time", &sleep_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_called", &last_called);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_ping_time", &last_ping_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_hist_time", &last_hist_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_hids", (void*)&last_hids);
      R__insp.InspectMember("vector<hid_t>", (void*)&last_hids, "last_hids.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "server_items", (void*)&server_items);
      R__insp.InspectMember("map<hid_t,TGListTreeItem*>", (void*)&server_items, "server_items.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hist_items", (void*)&hist_items);
      R__insp.InspectMember("map<hid_t,TGListTreeItem*>", (void*)&hist_items, "hist_items.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*canvas", &canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*listTree", &listTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*viewByObject", &viewByObject);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*viewByServer", &viewByServer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*folder_t", &folder_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ofolder_t", &ofolder_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h1_s", &h1_s);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h1_t", &h1_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h2_s", &h2_s);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h2_t", &h2_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h3_s", &h3_s);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h3_t", &h3_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pack_t", &pack_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hdisk_t", &hdisk_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*checked_t", &checked_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*unchecked_t", &unchecked_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tosave", &tosave);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "displaybar", &displaybar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*thefileinfo", &thefileinfo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hist_get_size", &hist_get_size);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "histtosave", (void*)&histtosave);
      R__insp.InspectMember("map<string,int>", (void*)&histtosave, "histtosave.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*verticalframe", &verticalframe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*progressbar", &progressbar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mainframe", &mainframe);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_Dialog_SaveHists(void *p) {
      delete ((::Dialog_SaveHists*)p);
   }
   static void deleteArray_Dialog_SaveHists(void *p) {
      delete [] ((::Dialog_SaveHists*)p);
   }
   static void destruct_Dialog_SaveHists(void *p) {
      typedef ::Dialog_SaveHists current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Dialog_SaveHists(TBuffer &buf, void *obj) {
      ((::Dialog_SaveHists*)obj)->::Dialog_SaveHists::Streamer(buf);
   }
} // end of namespace ROOT for class ::Dialog_SaveHists

namespace ROOT {
   void maplEhid_tcOTGListTreeItemmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEhid_tcOTGListTreeItemmUgR_Dictionary();
   static void *new_maplEhid_tcOTGListTreeItemmUgR(void *p = 0);
   static void *newArray_maplEhid_tcOTGListTreeItemmUgR(Long_t size, void *p);
   static void delete_maplEhid_tcOTGListTreeItemmUgR(void *p);
   static void deleteArray_maplEhid_tcOTGListTreeItemmUgR(void *p);
   static void destruct_maplEhid_tcOTGListTreeItemmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<hid_t,TGListTreeItem*>*)
   {
      map<hid_t,TGListTreeItem*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<hid_t,TGListTreeItem*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<hid_t,TGListTreeItem*>", -2, "prec_stl/map", 63,
                  typeid(map<hid_t,TGListTreeItem*>), DefineBehavior(ptr, ptr),
                  0, &maplEhid_tcOTGListTreeItemmUgR_Dictionary, isa_proxy, 0,
                  sizeof(map<hid_t,TGListTreeItem*>) );
      instance.SetNew(&new_maplEhid_tcOTGListTreeItemmUgR);
      instance.SetNewArray(&newArray_maplEhid_tcOTGListTreeItemmUgR);
      instance.SetDelete(&delete_maplEhid_tcOTGListTreeItemmUgR);
      instance.SetDeleteArray(&deleteArray_maplEhid_tcOTGListTreeItemmUgR);
      instance.SetDestructor(&destruct_maplEhid_tcOTGListTreeItemmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<hid_t,TGListTreeItem*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<hid_t,TGListTreeItem*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEhid_tcOTGListTreeItemmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<hid_t,TGListTreeItem*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEhid_tcOTGListTreeItemmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<hid_t,TGListTreeItem*> : new map<hid_t,TGListTreeItem*>;
   }
   static void *newArray_maplEhid_tcOTGListTreeItemmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<hid_t,TGListTreeItem*>[nElements] : new map<hid_t,TGListTreeItem*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEhid_tcOTGListTreeItemmUgR(void *p) {
      delete ((map<hid_t,TGListTreeItem*>*)p);
   }
   static void deleteArray_maplEhid_tcOTGListTreeItemmUgR(void *p) {
      delete [] ((map<hid_t,TGListTreeItem*>*)p);
   }
   static void destruct_maplEhid_tcOTGListTreeItemmUgR(void *p) {
      typedef map<hid_t,TGListTreeItem*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<hid_t,TGListTreeItem*>

namespace ROOT {
   void maplEstringcOintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOintgR_Dictionary();
   static void *new_maplEstringcOintgR(void *p = 0);
   static void *newArray_maplEstringcOintgR(Long_t size, void *p);
   static void delete_maplEstringcOintgR(void *p);
   static void deleteArray_maplEstringcOintgR(void *p);
   static void destruct_maplEstringcOintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<string,int>*)
   {
      map<string,int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,int>", -2, "map.dll", 0,
                  typeid(map<string,int>), DefineBehavior(ptr, ptr),
                  0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,int>) );
      instance.SetNew(&new_maplEstringcOintgR);
      instance.SetNewArray(&newArray_maplEstringcOintgR);
      instance.SetDelete(&delete_maplEstringcOintgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
      instance.SetDestructor(&destruct_maplEstringcOintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEstringcOintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
   }
   static void *newArray_maplEstringcOintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOintgR(void *p) {
      delete ((map<string,int>*)p);
   }
   static void deleteArray_maplEstringcOintgR(void *p) {
      delete [] ((map<string,int>*)p);
   }
   static void destruct_maplEstringcOintgR(void *p) {
      typedef map<string,int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<string,int>

namespace ROOT {
   void vectorlEhid_tgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEhid_tgR_Dictionary();
   static void *new_vectorlEhid_tgR(void *p = 0);
   static void *newArray_vectorlEhid_tgR(Long_t size, void *p);
   static void delete_vectorlEhid_tgR(void *p);
   static void deleteArray_vectorlEhid_tgR(void *p);
   static void destruct_vectorlEhid_tgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<hid_t>*)
   {
      vector<hid_t> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<hid_t>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<hid_t>", -2, "prec_stl/vector", 49,
                  typeid(vector<hid_t>), DefineBehavior(ptr, ptr),
                  0, &vectorlEhid_tgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<hid_t>) );
      instance.SetNew(&new_vectorlEhid_tgR);
      instance.SetNewArray(&newArray_vectorlEhid_tgR);
      instance.SetDelete(&delete_vectorlEhid_tgR);
      instance.SetDeleteArray(&deleteArray_vectorlEhid_tgR);
      instance.SetDestructor(&destruct_vectorlEhid_tgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<hid_t> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<hid_t>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEhid_tgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<hid_t>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEhid_tgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<hid_t> : new vector<hid_t>;
   }
   static void *newArray_vectorlEhid_tgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<hid_t>[nElements] : new vector<hid_t>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEhid_tgR(void *p) {
      delete ((vector<hid_t>*)p);
   }
   static void deleteArray_vectorlEhid_tgR(void *p) {
      delete [] ((vector<hid_t>*)p);
   }
   static void destruct_vectorlEhid_tgR(void *p) {
      typedef vector<hid_t> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<hid_t>

/********************************************************
* Dialog_SaveHists_Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDialog_SaveHists_Dict();

extern "C" void G__set_cpp_environmentDialog_SaveHists_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Dialog_SaveHists.h");
  G__cpp_reset_tagtableDialog_SaveHists_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevDialog_SaveHists_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Dialog_SaveHists */
static int G__Dialog_SaveHists_Dict_659_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Dialog_SaveHists* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Dialog_SaveHists(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) Dialog_SaveHists(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoTimer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoOK();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoCancel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoClickedEntry((TGListTreeItem*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoCheckedEntry((TObject*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->DoSave();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->AddDisplayBar();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->SaveHistograms();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Dialog_SaveHists*) G__getstructoffset())->AreHistosPresent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->GetAllHistos(*(vector<hid_t>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Dialog_SaveHists::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Dialog_SaveHists::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Dialog_SaveHists::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Dialog_SaveHists::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Dialog_SaveHists*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Dialog_SaveHists::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Dialog_SaveHists::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Dialog_SaveHists::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dialog_SaveHists_Dict_659_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Dialog_SaveHists::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Dialog_SaveHists G__TDialog_SaveHists;
static int G__Dialog_SaveHists_Dict_659_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Dialog_SaveHists*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Dialog_SaveHists*) (soff+(sizeof(Dialog_SaveHists)*i)))->~G__TDialog_SaveHists();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Dialog_SaveHists*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Dialog_SaveHists*) (soff))->~G__TDialog_SaveHists();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Dialog_SaveHists */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDialog_SaveHists_Dict {
 public:
  G__Sizep2memfuncDialog_SaveHists_Dict(): p(&G__Sizep2memfuncDialog_SaveHists_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDialog_SaveHists_Dict::*p)();
};

size_t G__get_sizep2memfuncDialog_SaveHists_Dict()
{
  G__Sizep2memfuncDialog_SaveHists_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDialog_SaveHists_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists))) {
     Dialog_SaveHists *G__Lderived;
     G__Lderived=(Dialog_SaveHists*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDialog_SaveHists_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<hid_t>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<hid_t,TGListTreeItem*>",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<hid_t,TGListTreeItem*,less<hid_t> >",117,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Dialog_SaveHists */
static void G__setup_memvarDialog_SaveHists(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists));
   { Dialog_SaveHists *p; p=(Dialog_SaveHists*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TTimer),-1,-1,4,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"sleep_time=",0,"in milliseconds");
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_called=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_ping_time=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_hist_time=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR),G__defined_typename("vector<hid_t>"),-1,4,"last_hids=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),G__defined_typename("map<hid_t,TGListTreeItem*>"),-1,4,"server_items=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),G__defined_typename("map<hid_t,TGListTreeItem*>"),-1,4,"hist_items=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGCanvas),-1,-1,4,"canvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGListTree),-1,-1,4,"listTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGRadioButton),-1,-1,4,"viewByObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGRadioButton),-1,-1,4,"viewByServer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"folder_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"ofolder_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h1_s=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h1_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h2_s=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h2_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h3_s=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"h3_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"pack_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"hdisk_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"checked_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGPicture),-1,-1,4,"unchecked_t=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"tosave=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"displaybar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGFileInfo),-1,-1,4,"thefileinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"hist_get_size=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->histtosave)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<string,int>"),-1,1,"histtosave=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->verticalframe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGVerticalFrame),-1,-1,1,"verticalframe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->progressbar)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGHProgressBar),-1,-1,1,"progressbar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mainframe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TGMainFrame),-1,-1,1,"mainframe=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDialog_SaveHists_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDialog_SaveHists(void) {
   /* Dialog_SaveHists */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists));
   G__memfunc_setup("Dialog_SaveHists",1609,G__Dialog_SaveHists_Dict_659_0_1, 105, G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTimer",692,G__Dialog_SaveHists_Dict_659_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoOK",333,G__Dialog_SaveHists_Dict_659_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoCancel",761,G__Dialog_SaveHists_Dict_659_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoClickedEntry",1396,G__Dialog_SaveHists_Dict_659_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - entry i - 'Int_t' 0 - btn", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoCheckedEntry",1388,G__Dialog_SaveHists_Dict_659_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TObject' - 0 - obj i - 'Int_t' 0 - check", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSave",578,G__Dialog_SaveHists_Dict_659_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddDisplayBar",1268,G__Dialog_SaveHists_Dict_659_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SaveHistograms",1456,G__Dialog_SaveHists_Dict_659_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AreHistosPresent",1651,G__Dialog_SaveHists_Dict_659_0_11, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAllHistos",1203,G__Dialog_SaveHists_Dict_659_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<hid_t,allocator<hid_t> >' 'vector<hid_t>' 1 - hids", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ParseFullPath",1307,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 0, 
"u 'string' - 1 - path u 'vector<string,allocator<string> >' 'vector<string>' 1 - dirs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateListTree",1423,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "u 'vector<hid_t,allocator<hid_t> >' 'vector<hid_t>' 0 - hids", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateGUI",825,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dialog_SaveHists_Dict_659_0_16, 85, G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Dialog_SaveHists::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dialog_SaveHists_Dict_659_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Dialog_SaveHists::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dialog_SaveHists_Dict_659_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Dialog_SaveHists::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dialog_SaveHists_Dict_659_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Dialog_SaveHists::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dialog_SaveHists_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dialog_SaveHists_Dict_659_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dialog_SaveHists_Dict_659_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Dialog_SaveHists::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dialog_SaveHists_Dict_659_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Dialog_SaveHists::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dialog_SaveHists_Dict_659_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Dialog_SaveHists::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dialog_SaveHists_Dict_659_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Dialog_SaveHists::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Dialog_SaveHists", 1735, G__Dialog_SaveHists_Dict_659_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDialog_SaveHists_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDialog_SaveHists_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDialog_SaveHists_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dialog_SaveHists_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGPicture = { "TGPicture" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGCanvas = { "TGCanvas" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGFileInfo = { "TGFileInfo" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TGHProgressBar = { "TGHProgressBar" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_Dialog_SaveHists = { "Dialog_SaveHists" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR = { "vector<hid_t,allocator<hid_t> >" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<hid_t,allocator<hid_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR = { "map<hid_t,TGListTreeItem*,less<hid_t>,allocator<pair<const hid_t,TGListTreeItem*> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDialog_SaveHists_Dict() {
  G__Dialog_SaveHists_DictLN_TClass.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TBuffer.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TMemberInspector.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TObject.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_string.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TTimer.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TQObject.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGWindow.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGPicture.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGObject.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGFrame.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGVerticalFrame.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGMainFrame.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGCanvas.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGRadioButton.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGListTreeItem.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGListTree.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGFileInfo.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TGHProgressBar.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_Dialog_SaveHists.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDialog_SaveHists_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_string);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGPicture);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGCanvas);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGListTreeItem);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGListTree);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGFileInfo);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TGHProgressBar);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_Dialog_SaveHists),sizeof(Dialog_SaveHists),-1,62464,(char*)NULL,G__setup_memvarDialog_SaveHists,G__setup_memfuncDialog_SaveHists);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR);
}
extern "C" void G__cpp_setupDialog_SaveHists_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupDialog_SaveHists_Dict()");
  G__set_cpp_environmentDialog_SaveHists_Dict();
  G__cpp_setup_tagtableDialog_SaveHists_Dict();

  G__cpp_setup_inheritanceDialog_SaveHists_Dict();

  G__cpp_setup_typetableDialog_SaveHists_Dict();

  G__cpp_setup_memvarDialog_SaveHists_Dict();

  G__cpp_setup_memfuncDialog_SaveHists_Dict();
  G__cpp_setup_globalDialog_SaveHists_Dict();
  G__cpp_setup_funcDialog_SaveHists_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDialog_SaveHists_Dict();
  return;
}
class G__cpp_setup_initDialog_SaveHists_Dict {
  public:
    G__cpp_setup_initDialog_SaveHists_Dict() { G__add_setup_func("Dialog_SaveHists_Dict",(G__incsetup)(&G__cpp_setupDialog_SaveHists_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDialog_SaveHists_Dict() { G__remove_setup_func("Dialog_SaveHists_Dict"); }
};
G__cpp_setup_initDialog_SaveHists_Dict G__cpp_setup_initializerDialog_SaveHists_Dict;

