/********************************************************************
* Dialog_SaveHists_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dialog_SaveHists_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDialog_SaveHists_Dict();
extern void G__cpp_setup_inheritanceDialog_SaveHists_Dict();
extern void G__cpp_setup_typetableDialog_SaveHists_Dict();
extern void G__cpp_setup_memvarDialog_SaveHists_Dict();
extern void G__cpp_setup_globalDialog_SaveHists_Dict();
extern void G__cpp_setup_memfuncDialog_SaveHists_Dict();
extern void G__cpp_setup_funcDialog_SaveHists_Dict();
extern void G__set_cpp_environmentDialog_SaveHists_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Dialog_SaveHists.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TClass;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TBuffer;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TMemberInspector;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TObject;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_string;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TTimer;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TQObject;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGWindow;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGPicture;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGObject;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGFrame;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGVerticalFrame;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGMainFrame;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGCanvas;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGRadioButton;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGListTreeItem;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGListTree;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGFileInfo;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TGHProgressBar;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_Dialog_SaveHists;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dialog_SaveHists_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR;

/* STUB derived class for protected member access */
