/********************************************************************
* rs_mainframe_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rs_mainframe_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablers_mainframe_Dict();
extern void G__cpp_setup_inheritancers_mainframe_Dict();
extern void G__cpp_setup_typetablers_mainframe_Dict();
extern void G__cpp_setup_memvarrs_mainframe_Dict();
extern void G__cpp_setup_globalrs_mainframe_Dict();
extern void G__cpp_setup_memfuncrs_mainframe_Dict();
extern void G__cpp_setup_funcrs_mainframe_Dict();
extern void G__set_cpp_environmentrs_mainframe_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rs_mainframe.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rs_mainframe_DictLN_TClass;
extern G__linked_taginfo G__rs_mainframe_DictLN_TBuffer;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMemberInspector;
extern G__linked_taginfo G__rs_mainframe_DictLN_TObject;
extern G__linked_taginfo G__rs_mainframe_DictLN_string;
extern G__linked_taginfo G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TTimer;
extern G__linked_taginfo G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TQObject;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGWindow;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGObject;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGFrame;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGTextButton;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGMainFrame;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGCheckButton;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGRadioButton;
extern G__linked_taginfo G__rs_mainframe_DictLN_TCanvas;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGComboBox;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_TGLabel;
extern G__linked_taginfo G__rs_mainframe_DictLN_TH1;
extern G__linked_taginfo G__rs_mainframe_DictLN_TFile;
extern G__linked_taginfo G__rs_mainframe_DictLN_hid_t;
extern G__linked_taginfo G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_hdef_t;
extern G__linked_taginfo G__rs_mainframe_DictLN_hdef_tcLcLhistdimension_t;
extern G__linked_taginfo G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__rs_mainframe_DictLN_rs_mainframe;
extern G__linked_taginfo G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs;

/* STUB derived class for protected member access */
