//
// File generated by rootcint at Tue Sep 24 18:06:40 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rs_mainframe_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rs_mainframe_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void rs_mainframe_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_rs_mainframe(void *p);
   static void deleteArray_rs_mainframe(void *p);
   static void destruct_rs_mainframe(void *p);
   static void streamer_rs_mainframe(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::rs_mainframe*)
   {
      ::rs_mainframe *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::rs_mainframe >(0);
      static ::ROOT::TGenericClassInfo 
         instance("rs_mainframe", ::rs_mainframe::Class_Version(), "./rs_mainframe.h", 40,
                  typeid(::rs_mainframe), DefineBehavior(ptr, ptr),
                  &::rs_mainframe::Dictionary, isa_proxy, 0,
                  sizeof(::rs_mainframe) );
      instance.SetDelete(&delete_rs_mainframe);
      instance.SetDeleteArray(&deleteArray_rs_mainframe);
      instance.SetDestructor(&destruct_rs_mainframe);
      instance.SetStreamerFunc(&streamer_rs_mainframe);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::rs_mainframe*)
   {
      return GenerateInitInstanceLocal((::rs_mainframe*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::rs_mainframe*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *rs_mainframe::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *rs_mainframe::Class_Name()
{
   return "rs_mainframe";
}

//______________________________________________________________________________
const char *rs_mainframe::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rs_mainframe*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int rs_mainframe::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rs_mainframe*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void rs_mainframe::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rs_mainframe*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *rs_mainframe::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rs_mainframe*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void rs_mainframe::Streamer(TBuffer &R__b)
{
   // Stream an object of class rs_mainframe.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TGMainFrame::Streamer(R__b);
      R__b >> dialog_selectserverhist;
      R__b >> dialog_selecthists;
      R__b >> dialog_savehists;
      R__b >> dialog_indivhists;
      R__b >> dialog_selecttree;
      R__b >> selected_server;
      R__b >> selected_hist;
      R__b >> retrieved_lab;
      R__b >> delay;
      R__b >> canvas;
      R__b >> auto_refresh;
      R__b >> loop_over_servers;
      R__b >> loop_over_hists;
      R__b >> show_archived_hists;
      R__b >> indiv;
      R__b >> delete_dialog_selectserverhist;
      R__b >> delete_dialog_selecttree;
      R__b >> delete_dialog_selecthists;
      R__b >> delete_dialog_savehists;
      R__b >> delete_dialog_indivhists;
      R__b >> can_view_indiv;
      void *ptr_viewStyle_rs = (void*)&viewStyle_rs;
      R__b >> *reinterpret_cast<Int_t*>(ptr_viewStyle_rs);
      R__b >> timer;
      R__b >> sleep_time;
      R__b >> last_called;
      R__b >> last_ping_time;
      R__b >> last_hist_requested;
      R__b >> VBServer;
      R__b >> delay_time;
      R__b.StreamObject(&(last_requested),typeid(hid_t));
      R__b >> last_hist_plotted;
      R__b >> archive_file;
      R__b.CheckByteCount(R__s, R__c, rs_mainframe::IsA());
   } else {
      R__c = R__b.WriteVersion(rs_mainframe::IsA(), kTRUE);
      TGMainFrame::Streamer(R__b);
      R__b << dialog_selectserverhist;
      R__b << dialog_selecthists;
      R__b << dialog_savehists;
      R__b << dialog_indivhists;
      R__b << dialog_selecttree;
      R__b << selected_server;
      R__b << selected_hist;
      R__b << retrieved_lab;
      R__b << delay;
      R__b << canvas;
      R__b << auto_refresh;
      R__b << loop_over_servers;
      R__b << loop_over_hists;
      R__b << show_archived_hists;
      R__b << indiv;
      R__b << delete_dialog_selectserverhist;
      R__b << delete_dialog_selecttree;
      R__b << delete_dialog_selecthists;
      R__b << delete_dialog_savehists;
      R__b << delete_dialog_indivhists;
      R__b << can_view_indiv;
      R__b << (Int_t)viewStyle_rs;
      R__b << timer;
      R__b << sleep_time;
      R__b << last_called;
      R__b << last_ping_time;
      R__b << last_hist_requested;
      R__b << VBServer;
      R__b << delay_time;
      R__b.StreamObject(&(last_requested),typeid(hid_t));
      R__b << last_hist_plotted;
      R__b << archive_file;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void rs_mainframe::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class rs_mainframe.
      TClass *R__cl = ::rs_mainframe::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dialog_selectserverhist", &dialog_selectserverhist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dialog_selecthists", &dialog_selecthists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dialog_savehists", &dialog_savehists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dialog_indivhists", &dialog_indivhists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dialog_selecttree", &dialog_selecttree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*selected_server", &selected_server);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*selected_hist", &selected_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*retrieved_lab", &retrieved_lab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*delay", &delay);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*canvas", &canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*auto_refresh", &auto_refresh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*loop_over_servers", &loop_over_servers);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*loop_over_hists", &loop_over_hists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*show_archived_hists", &show_archived_hists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*indiv", &indiv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delete_dialog_selectserverhist", &delete_dialog_selectserverhist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delete_dialog_selecttree", &delete_dialog_selecttree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delete_dialog_selecthists", &delete_dialog_selecthists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delete_dialog_savehists", &delete_dialog_savehists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delete_dialog_indivhists", &delete_dialog_indivhists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "can_view_indiv", &can_view_indiv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "viewStyle_rs", &viewStyle_rs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*timer", &timer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sleep_time", &sleep_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_called", &last_called);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_ping_time", &last_ping_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_hist_requested", &last_hist_requested);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*VBServer", &VBServer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delay_time", &delay_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "last_requested", (void*)&last_requested);
      R__insp.InspectMember("hid_t", (void*)&last_requested, "last_requested.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*last_hist_plotted", &last_hist_plotted);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*archive_file", &archive_file);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_rs_mainframe(void *p) {
      delete ((::rs_mainframe*)p);
   }
   static void deleteArray_rs_mainframe(void *p) {
      delete [] ((::rs_mainframe*)p);
   }
   static void destruct_rs_mainframe(void *p) {
      typedef ::rs_mainframe current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_rs_mainframe(TBuffer &buf, void *obj) {
      ((::rs_mainframe*)obj)->::rs_mainframe::Streamer(buf);
   }
} // end of namespace ROOT for class ::rs_mainframe

/********************************************************
* rs_mainframe_Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablers_mainframe_Dict();

extern "C" void G__set_cpp_environmentrs_mainframe_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("rs_mainframe.h");
  G__cpp_reset_tagtablers_mainframe_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevrs_mainframe_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* rs_mainframe */
static int G__rs_mainframe_Dict_795_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rs_mainframe* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new rs_mainframe(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) rs_mainframe(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->ReadPreferences();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->SavePreferences();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoQuit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->MakeTB();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoTimer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoSelectHists();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoSelectDelay((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoUpdate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoNext();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoPrev();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoLoopOverServers();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoLoopOverHists();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoSave();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoSaveHists();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoFinal();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoIndiv();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoTreeInfo();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoTreeInfoShort();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoOnline();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->DoSetArchiveFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) rs_mainframe::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rs_mainframe::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) rs_mainframe::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      rs_mainframe::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rs_mainframe*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rs_mainframe::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rs_mainframe::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rs_mainframe::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rs_mainframe_Dict_795_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rs_mainframe::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef rs_mainframe G__Trs_mainframe;
static int G__rs_mainframe_Dict_795_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (rs_mainframe*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((rs_mainframe*) (soff+(sizeof(rs_mainframe)*i)))->~G__Trs_mainframe();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (rs_mainframe*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((rs_mainframe*) (soff))->~G__Trs_mainframe();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* rs_mainframe */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrs_mainframe_Dict {
 public:
  G__Sizep2memfuncrs_mainframe_Dict(): p(&G__Sizep2memfuncrs_mainframe_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrs_mainframe_Dict::*p)();
};

size_t G__get_sizep2memfuncrs_mainframe_Dict()
{
  G__Sizep2memfuncrs_mainframe_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancers_mainframe_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe))) {
     rs_mainframe *G__Lderived;
     G__Lderived=(rs_mainframe*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe),G__get_linked_tagnum(&G__rs_mainframe_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablers_mainframe_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<hid_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<hid_t,TGListTreeItem*>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<hid_t,TGListTreeItem*,less<hid_t> >",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,hinfo_t>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,hinfo_t,less<string> >",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* rs_mainframe */
static void G__setup_memvarrs_mainframe(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe));
   { rs_mainframe *p; p=(rs_mainframe*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs),-1,-2,1,G__FastAllocString(2048).Format("kViewByObject_rs=%lldLL",(long long)rs_mainframe::kViewByObject_rs).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs),-1,-2,1,G__FastAllocString(2048).Format("kViewByServer_rs=%lldLL",(long long)rs_mainframe::kViewByServer_rs).data(),0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dialog_selectserverhist)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),-1,-1,1,"dialog_selectserverhist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dialog_selecthists)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),-1,-1,1,"dialog_selecthists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dialog_savehists)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),-1,-1,1,"dialog_savehists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dialog_indivhists)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),-1,-1,1,"dialog_indivhists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dialog_selecttree)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGMainFrame),-1,-1,1,"dialog_selecttree=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->selected_server)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGLabel),-1,-1,1,"selected_server=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->selected_hist)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGLabel),-1,-1,1,"selected_hist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->retrieved_lab)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGLabel),-1,-1,1,"retrieved_lab=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delay)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGComboBox),-1,-1,1,"delay=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->canvas)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TCanvas),-1,-1,1,"canvas=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->auto_refresh)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGCheckButton),-1,-1,1,"auto_refresh=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->loop_over_servers)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGCheckButton),-1,-1,1,"loop_over_servers=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->loop_over_hists)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGCheckButton),-1,-1,1,"loop_over_hists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->show_archived_hists)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGCheckButton),-1,-1,1,"show_archived_hists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->indiv)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGTextButton),-1,-1,1,"indiv=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delete_dialog_selectserverhist)-(long)(p)),103,0,0,-1,-1,-1,1,"delete_dialog_selectserverhist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delete_dialog_selecttree)-(long)(p)),103,0,0,-1,-1,-1,1,"delete_dialog_selecttree=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delete_dialog_selecthists)-(long)(p)),103,0,0,-1,-1,-1,1,"delete_dialog_selecthists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delete_dialog_savehists)-(long)(p)),103,0,0,-1,-1,-1,1,"delete_dialog_savehists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->delete_dialog_indivhists)-(long)(p)),103,0,0,-1,-1,-1,1,"delete_dialog_indivhists=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->can_view_indiv)-(long)(p)),103,0,0,-1,-1,-1,1,"can_view_indiv=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs),-1,-1,2,"viewStyle_rs=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TTimer),-1,-1,4,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"sleep_time=",0,"in milliseconds");
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_called=",0,"last time DoTimer() was called");
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_ping_time=",0,"last time we broadcast for a server list");
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"last_hist_requested=",0,"last time we requested a histogram (see rs_info for time we actually got it)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TGRadioButton),-1,-1,4,"VBServer=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"delay_time=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_hid_t),-1,-1,4,"last_requested=",0,"last hnamepath requested");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TH1),-1,-1,4,"last_hist_plotted=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TFile),-1,-1,4,"archive_file=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rs_mainframe_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrs_mainframe_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncrs_mainframe(void) {
   /* rs_mainframe */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe));
   G__memfunc_setup("rs_mainframe",1268,G__rs_mainframe_Dict_795_0_1, 105, G__get_linked_tagnum(&G__rs_mainframe_DictLN_rs_mainframe), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadPreferences",1518,G__rs_mainframe_Dict_795_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SavePreferences",1537,G__rs_mainframe_Dict_795_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoQuit",598,G__rs_mainframe_Dict_795_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeTB",532,G__rs_mainframe_Dict_795_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTimer",692,G__rs_mainframe_Dict_795_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectHists",1310,G__rs_mainframe_Dict_795_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectDelay",1282,G__rs_mainframe_Dict_795_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoUpdate",790,G__rs_mainframe_Dict_795_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNext",594,G__rs_mainframe_Dict_795_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoPrev",592,G__rs_mainframe_Dict_795_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoLoopOverServers",1747,G__rs_mainframe_Dict_795_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoLoopOverHists",1524,G__rs_mainframe_Dict_795_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSave",578,G__rs_mainframe_Dict_795_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSaveHists",1101,G__rs_mainframe_Dict_795_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFinal",669,G__rs_mainframe_Dict_795_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoIndiv",685,G__rs_mainframe_Dict_795_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DoTreeInfo",975,G__rs_mainframe_Dict_795_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTreeInfoShort",1503,G__rs_mainframe_Dict_795_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoOnline",792,G__rs_mainframe_Dict_795_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSetArchiveFile",1569,G__rs_mainframe_Dict_795_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawHist",806,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 2, 0, 
"U 'TH1' - 0 - hist u 'string' - 0 - hnamepath "
"i 'hdef_t::histdimension_t' - 0 - hdim", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateGUI",825,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rs_mainframe_Dict_795_0_25, 85, G__get_linked_tagnum(&G__rs_mainframe_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&rs_mainframe::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rs_mainframe_Dict_795_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rs_mainframe::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rs_mainframe_Dict_795_0_27, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&rs_mainframe::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rs_mainframe_Dict_795_0_28, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&rs_mainframe::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rs_mainframe_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rs_mainframe_Dict_795_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rs_mainframe_Dict_795_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rs_mainframe::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rs_mainframe_Dict_795_0_34, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rs_mainframe::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rs_mainframe_Dict_795_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rs_mainframe::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rs_mainframe_Dict_795_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rs_mainframe::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~rs_mainframe", 1394, G__rs_mainframe_Dict_795_0_37, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrs_mainframe_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrs_mainframe_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrs_mainframe_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rs_mainframe_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_hid_t = { "hid_t" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR = { "vector<hid_t,allocator<hid_t> >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<hid_t,allocator<hid_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR = { "map<hid_t,TGListTreeItem*,less<hid_t>,allocator<pair<const hid_t,TGListTreeItem*> > >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_hdef_t = { "hdef_t" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_hdef_tcLcLhistdimension_t = { "hdef_t::histdimension_t" , 101 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR = { "map<string,hinfo_t,less<string>,allocator<pair<const string,hinfo_t> > >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_rs_mainframe = { "rs_mainframe" , 99 , -1 };
G__linked_taginfo G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs = { "rs_mainframe::viewStyle_t_rs" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablers_mainframe_Dict() {
  G__rs_mainframe_DictLN_TClass.tagnum = -1 ;
  G__rs_mainframe_DictLN_TBuffer.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMemberInspector.tagnum = -1 ;
  G__rs_mainframe_DictLN_TObject.tagnum = -1 ;
  G__rs_mainframe_DictLN_string.tagnum = -1 ;
  G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TTimer.tagnum = -1 ;
  G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TQObject.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGWindow.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGObject.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGFrame.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGTextButton.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGMainFrame.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGCheckButton.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGRadioButton.tagnum = -1 ;
  G__rs_mainframe_DictLN_TCanvas.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGComboBox.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_TGLabel.tagnum = -1 ;
  G__rs_mainframe_DictLN_TH1.tagnum = -1 ;
  G__rs_mainframe_DictLN_TFile.tagnum = -1 ;
  G__rs_mainframe_DictLN_hid_t.tagnum = -1 ;
  G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_hdef_t.tagnum = -1 ;
  G__rs_mainframe_DictLN_hdef_tcLcLhistdimension_t.tagnum = -1 ;
  G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__rs_mainframe_DictLN_rs_mainframe.tagnum = -1 ;
  G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablers_mainframe_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_string);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TH1);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_TFile);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_hid_t);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_vectorlEhid_tcOallocatorlEhid_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEhid_tcOallocatorlEhid_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_maplEhid_tcOTGListTreeItemmUcOlesslEhid_tgRcOallocatorlEpairlEconstsPhid_tcOTGListTreeItemmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_hdef_t);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_hdef_tcLcLhistdimension_t);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_maplEstringcOhinfo_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOhinfo_tgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_rs_mainframe),sizeof(rs_mainframe),-1,62464,(char*)NULL,G__setup_memvarrs_mainframe,G__setup_memfuncrs_mainframe);
   G__get_linked_tagnum_fwd(&G__rs_mainframe_DictLN_rs_mainframecLcLviewStyle_t_rs);
}
extern "C" void G__cpp_setuprs_mainframe_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprs_mainframe_Dict()");
  G__set_cpp_environmentrs_mainframe_Dict();
  G__cpp_setup_tagtablers_mainframe_Dict();

  G__cpp_setup_inheritancers_mainframe_Dict();

  G__cpp_setup_typetablers_mainframe_Dict();

  G__cpp_setup_memvarrs_mainframe_Dict();

  G__cpp_setup_memfuncrs_mainframe_Dict();
  G__cpp_setup_globalrs_mainframe_Dict();
  G__cpp_setup_funcrs_mainframe_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrs_mainframe_Dict();
  return;
}
class G__cpp_setup_initrs_mainframe_Dict {
  public:
    G__cpp_setup_initrs_mainframe_Dict() { G__add_setup_func("rs_mainframe_Dict",(G__incsetup)(&G__cpp_setuprs_mainframe_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrs_mainframe_Dict() { G__remove_setup_func("rs_mainframe_Dict"); }
};
G__cpp_setup_initrs_mainframe_Dict G__cpp_setup_initializerrs_mainframe_Dict;

