
import os

import sbms

# get env object and clone it
Import('*')
env = env.Clone()

sbms.AddROOT(env)
sbms.AddCMSG(env)
sbms.AddXMSG(env)
env.PrependUnique(LIBS=['RootSpy-client', 'curl', 'ASImage'])   # n.b. ASImage is to provide ROOTs TASImage class

# This a temporary fix to avoid requiring 
# the gcc 4.8 compiler
env.AppendUnique(CCFLAGS='-DNO_CODAOBJECTROOT')

codalibdir = '%s/Linux-x86_64/lib' % os.getenv('CODA', '/')

if os.path.exists(codalibdir):
	env.AppendUnique(LIBPATH=codalibdir, LIBS='codaObject')
else:
	env.AppendUnique(CCFLAGS='-DNO_CODAOBJECTROOT')
	
sbms.executable(env)

