
Import('*')

subdirs = ['libRootSpy', 'libRootSpy-client']
subdirs.extend(['RootSpy', 'RSArchiver', 'RSDumpTree'])
subdirs.extend(['plugins'])
subdirs.extend(['examples'])

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

